///Auth actions
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_GET_ROLE = 'AUTH_GET_ROLE';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_ALL_ROLES = 'AUTH_ALL_ROLES';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

//Notifications actions
export const NOTIFICATIONS_GET_ALL = 'NOTIFICATIONS_GET_ALL';
export const NOTIFICATIONS_ADD = 'NOTIFICATIONS_ADD';
export const NOTIFICATIONS_DELETE = 'NOTIFICATIONS_DELETE';

//translations actions
export const TRANSLATIONS_CHANGE_LANG = 'TRANSLATIONS_CHANGE_LANG';
export const TRANSLATIONS_ADDING_LANGUAGES = 'TRANSLATIONS_ADDING_LANGUAGES';


//pokemons
export const POKEMON_TYPES_START = 'POKEMON_TYPES_START';
export const POKEMON_START = 'POKEMON_START';
export const POKEMON_GET_ALL = 'POKEMON_GET_ALL';
export const POKEMON_ADD_TO_POKEDEX = 'POKEMON_ADD_TO_POKEDEX';
export const POKEMON_REMOVE_FROM_POKEDEX = 'POKEMON_REMOVE_FROM_POKEDEX';
export const POKEMON_TYPES_ALL = 'POKEMON_TYPES_ALL';
export const POKEMON_FAIL = 'POKEMON_FAIL';
export const POKEMON_FILTER = "POKEMON_FILTER";
export const POKEMON_CHANGE_TRANSLATIONS = "POKEMON_CHANGE_TRANSLATIONS";
export const POKEMON_BASE_START ="POKEMON_BASE_START";
export const POKEMON_GET_BASE ="POKEMON_GET_BASE";







